### ISSUE TITLE
issues running bot

### ISSUE THREAD

**Issue by vonhex** [dab-bot/ComfyUI-SDXL-DiscordBot#10]
I get this as soon as I open the app.

[2023-12-03 09:06:46] [INFO    ] discord.client: logging in using static token
Traceback (most recent call last):
  File "aiohttp\connector.py", line 980, in _wrap_create_connection
  File "asyncio\base_events.py", line 1103, in create_connection
  File "asyncio\base_events.py", line 1133, in _create_connection_transport
  File "asyncio\sslproto.py", line 534, in data_received
  File "asyncio\sslproto.py", line 188, in feed_ssldata
  File "ssl.py", line 975, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bot.py", line 155, in <module>
  File "discord\client.py", line 860, in run
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "discord\client.py", line 849, in runner
  File "discord\client.py", line 777, in start
  File "discord\client.py", line 612, in login
  File "discord\http.py", line 803, in static_login
  File "discord\http.py", line 625, in request
  File "aiohttp\client.py", line 1141, in __aenter__
  File "aiohttp\client.py", line 536, in _request
  File "aiohttp\connector.py", line 540, in connect
  File "aiohttp\connector.py", line 901, in _create_connection
  File "aiohttp\connector.py", line 1209, in _create_direct_connection
  File "aiohttp\connector.py", line 1178, in _create_direct_connection
  File "aiohttp\connector.py", line 982, in _wrap_create_connection
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')]
[

**Comment by vonhex** [comment]
Now it randomly started working but I get this when generating

[2023-12-03 09:53:11] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'imagine'
Traceback (most recent call last):
  File "discord\app_commands\commands.py", line 828, in _do_call
  File "bot.py", line 148, in slash_command
  File "imageGen.py", line 101, in generate_images
  File "imageGen.py", line 58, in connect
  File "websockets\legacy\client.py", line 655, in __await_impl_timeout__
  File "websockets\legacy\client.py", line 659, in __await_impl__
  File "asyncio\base_events.py", line 1036, in create_connection
  File "asyncio\base_events.py", line 1418, in _ensure_resolved
  File "asyncio\base_events.py", line 863, in getaddrinfo
  File "concurrent\futures\thread.py", line 58, in run
  File "socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "discord\app_commands\tree.py", line 1248, in _call
  File "discord\app_commands\commands.py", line 853, in _invoke_with_namespace
  File "discord\app_commands\commands.py", line 846, in _do_call
discord.app_commands.errors.CommandInvokeError: Command 'imagine' raised an exception: gaierror: [Errno 11001] getaddrinfo failed
