### ISSUE TITLE
Custom Workflow for SDXL Turbo

### ISSUE THREAD

**Issue by vonhex** [dab-bot/ComfyUI-SDXL-DiscordBot#11]
Im trying to get turbo to work with discord and I keep getting this error when prompting the bot

[2023-12-03 10:43:02] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'imagine'
Traceback (most recent call last):
  File "discord\app_commands\commands.py", line 828, in _do_call
  File "bot.py", line 152, in slash_command
  File "bot.py", line 40, in create_collage
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "discord\app_commands\tree.py", line 1248, in _call
  File "discord\app_commands\commands.py", line 853, in _invoke_with_namespace
  File "discord\app_commands\commands.py", line 846, in _do_call
discord.app_commands.errors.CommandInvokeError: Command 'imagine' raised an exception: ZeroDivisionError: division by zero

**Comment by wtfreely** [comment]
Hi, did you solve this?  I'm running into it too.

**Comment by vonhex** [comment]
I did! The bot only likes the regular sampler, so make sure it's not custom or advanced, make sure the nodes are properly numbered in the config, and change the saved image output to final_output, if you get a 400 error you are missing a module or model. Hope that helps!

If I remember correctly it's the output name that solved this error.
