### ISSUE TITLE
Is it possible to use turbo models? None seem to work

### ISSUE THREAD

**Issue by REDDKOMET** [dab-bot/ComfyUI-SDXL-DiscordBot#15]
Whenever I add a Turbo model I get errors, my workflow is just an edited version of the main one. I know my discord bot is set up correctly because it works fine with the default files.

Errors:
[2024-01-12 11:13:22] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'imagine'
Traceback (most recent call last):
  File "discord\app_commands\commands.py", line 828, in _do_call
  File "bot.py", line 148, in slash_command
  File "imageGen.py", line 110, in generate_images
KeyError: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "discord\app_commands\tree.py", line 1248, in _call
  File "discord\app_commands\commands.py", line 853, in _invoke_with_namespace
  File "discord\app_commands\commands.py", line 846, in _do_call
discord.app_commands.errors.CommandInvokeError: Command 'imagine' raised an exception: KeyError: ''

[img2img_config.json](https://github.com/dab-bot/ComfyUI-SDXL-DiscordBot/files/13921414/img2img_config.json)
[text2img_config.json](https://github.com/dab-bot/ComfyUI-SDXL-DiscordBot/files/13921415/text2img_config.json)
[upscale_config.json](https://github.com/dab-bot/ComfyUI-SDXL-DiscordBot/files/13921416/upscale_config.json)
[config.txt](https://github.com/dab-bot/ComfyUI-SDXL-DiscordBot/files/13921424/config.txt)

**Comment by erroneousau** [comment]
I've just had a look at your config and text2img config files and looks like you've set the negative prompt to node 26 which doesn't exist in the text2img config. Looks like that should be 13.

**Comment by REDDKOMET** [comment]
Thanks, that fixed txt2img but other two do not work:

[2024-06-28 11:56:41] [ERROR   ] discord.ui.view: Ignoring exception in view <Buttons timeout=180 children=9> for item <ImageButton style=<ButtonStyle.secondary: 2> url=None disabled=False label='V1' emoji=<PartialEmoji animated=False name='♻️' id=None> row=1>
Traceback (most recent call last):
  File "discord\ui\view.py", line 427, in _scheduled_task
  File "bot.py", line 81, in callback
  File "bot.py", line 113, in generate_alternatives_and_send
  File "imageGen.py", line 144, in generate_alternatives
KeyError: '2'
