### ISSUE TITLE
"Invalid Webhook Token"

### ISSUE THREAD

**Issue by TheMeIonGod** [dab-bot/ComfyUI-SDXL-DiscordBot#2]
I keep getting this error. I know the actual discord token is correct because it shows the Bot online when it is running and the /imagine command appears to be "working". The images are being put in the "out" folder but they never get posted to the discord by the bot.

[2023-08-24 22:20:52] [INFO    ] discord.gateway: Shard ID None has successfully RESUMED session ed76b5d0a9bc902d8a562a858f8aecf7.
[2023-08-24 22:20:55] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'imagine'
Traceback (most recent call last):
  File "discord\app_commands\commands.py", line 828, in _do_call
  File "bot.py", line 152, in slash_command
  File "discord\webhook\async_.py", line 1805, in send
  File "discord\webhook\async_.py", line 221, in request
discord.errors.HTTPException: 401 Unauthorized (error code: 50027): Invalid Webhook Token

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "discord\app_commands\tree.py", line 1248, in _call
  File "discord\app_commands\commands.py", line 853, in _invoke_with_namespace
  File "discord\app_commands\commands.py", line 846, in _do_call
discord.app_commands.errors.CommandInvokeError: Command 'imagine' raised an exception: HTTPException: 401 Unauthorized (error code: 50027): Invalid Webhook Token

**Comment by TheMeIonGod** [comment]
> Could you show me the workflow you were using? are the output images using the "final_output" prefix?
I don't know if I know exactly what you mean. It is a brand new install of ComfyUI with only the SDXL base and refiner models plus the Lora added to it (Plus a port change and --listen). By default the prefix was "ComfyUI" I change it to "final_output" The images in the out folder appear just be images_dateandtime.png Here is the TEXT2IMG config: [API_TEXT2IMG]
ENGINE=stable-diffusion-xl-1024-v1-0
CFG=8
WIDTH=1024
HEIGHT=1024
SAMPLES=4
SAMPLER=euler
STEPS=30
![image](https://github.com/dab-bot/ComfyUI-SDXL-DiscordBot/assets/51935225/52f86ac0-ba2c-4170-8158-930be72b7898)

**Comment by TheMeIonGod** [comment]
> All good, was more curious if you were using a custom workflow config, I think most likely issue would then be generation time, I think discord by default closes the webhook after 3 minutes of inactivity. Would you say the images take longer than that to generate?

When originally loading the model yes. But once it is loaded it is much quicker. Problem is it seems to want to reload the model when a different client is used on it (Like It will stay loaded if I use the WebUI multiple times but it from what I have seen, using the bot it has tried to reload the model every request). I have seen another bot similar to this that has an updating progress perhaps something like that would help?

**Comment by TheMeIonGod** [comment]
> Link to new release here, try it out and let me know how it goes 😄: https://github.com/dab-bot/ComfyUI-SDXL-DiscordBot/releases/tag/V1.0.1

I tried it on my Main PC and got it to work, though it should also work on my server.
I moved ComfyUI to an SSD but it still is not faster than 3 minutes. Though I am getting this error now with that new release on my server and Main PC. Once this error is thrown the bot is still shown online but it stops posting images and nothing is put in the "out" folder. I think this is the current main cause why my server is not working with it, but again I have also have had it happen on my main PC:

[2023-08-25 09:01:09] [ERROR   ] discord.app_commands.tree: Ignoring exception in command 'imagine'
Traceback (most recent call last):
  File "websockets\legacy\protocol.py", line 959, in transfer_data
  File "websockets\legacy\protocol.py", line 1029, in read_message
  File "websockets\legacy\protocol.py", line 1104, in read_data_frame
  File "websockets\legacy\protocol.py", line 1161, in read_frame
  File "websockets\legacy\framing.py", line 68, in read
  File "asyncio\streams.py", line 708, in readexactly
  File "asyncio\streams.py", line 501, in _wait_for_data
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "discord\app_commands\commands.py", line 828, in _do_call
  File "bot.py", line 148, in slash_command
  File "imageGen.py", line 116, in generate_images
  File "imageGen.py", line 67, in get_images
  File "websockets\legacy\protocol.py", line 497, in __aiter__
  File "websockets\legacy\protocol.py", line 568, in recv
  File "websockets\legacy\protocol.py", line 944, in ensure_open
websockets.exceptions.ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "discord\app_commands\tree.py", line 1248, in _call
  File "discord\app_commands\commands.py", line 853, in _invoke_with_namespace
  File "discord\app_commands\commands.py", line 846, in _do_call
discord.app_commands.errors.CommandInvokeError: Command 'imagine' raised an exception: ConnectionClosedError: sent 1011 (unexpected error) keepalive ping timeout; no close frame received
