### ISSUE TITLE
discord.app_commands.errors.CommandInvokeError: Command 'imagine' raised an exception: KeyError: '321'

### ISSUE THREAD

**Issue by ezra-ch** [dab-bot/ComfyUI-SDXL-DiscordBot#5]
```    
  "id": 321,
      "type": "CLIPTextEncode",
      "pos": [
        -300,
        975
      ],
      "size": {
        "0": 407.1927490234375,
        "1": 87.56219482421875
      },
      "flags": {},
      "order": 9,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 879,
          "slot_index": 0
        }
      ],
      "outputs": [
        {
          "name": "CONDITIONING",
          "type": "CONDITIONING",
          "links": [
            921
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "title": "Prompt",
      "properties": {
        "Node name for S&R": "CLIPTextEncode"
      },
      "widgets_values": [
        "LOL"
      ],
      "color": "#232",
      "bgcolor": "#353"
    },
```

**Comment by ezra-ch** [comment]
its literally the right id

**Comment by ezra-ch** [comment]
```
Traceback (most recent call last):
  File "discord\app_commands\tree.py", line 1248, in _call
  File "discord\app_commands\commands.py", line 853, in _invoke_with_namespace
  File "discord\app_commands\commands.py", line 846, in _do_call
discord.app_commands.errors.CommandInvokeError: Command 'imagine' raised an exception: KeyError: '321'

**Comment by ezra-ch** [comment]
heres the workflow.json

```
{
  "last_node_id": 506,
  "last_link_id": 923,
  "nodes": [
    {
      "id": 334,
      "type": "VAEDecode",
      "pos": [
        1050,
        639
      ],
      "size": {
        "0": 210,
        "1": 46
      },
      "flags": {},
      "order": 11,
      "mode": 0,
      "inputs": [
        {
          "name": "samples",
          "type": "LATENT",
          "link": 890,
          "slot_index": 0
        },
        {
          "name": "vae",
          "type": "VAE",
          "link": 913,
          "slot_index": 1
        }
      ],
      "outputs": [
        {
          "name": "IMAGE",
          "type": "IMAGE",
          "links": [
            850,
            916
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "VAEDecode"
      },
      "color": "#322",
      "bgcolor": "#533"
    },
    {
      "id": 486,
      "type": "ADE_AnimateDiffLoaderV1Advanced",
      "pos": [
        247,
        648
      ],
      "size": {
        "0": 336.47369384765625,
        "1": 228.05734252929688
      },
      "flags": {},
      "order": 6,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "MODEL",
          "link": 909,
          "slot_index": 0
        },
        {
          "name": "latents",
          "type": "LATENT",
          "link": 905,
          "slot_index": 1
        }
      ],
      "outputs": [
        {
          "name": "MODEL",
          "type": "MODEL",
          "links": [
            894
          ],
          "shape": 3,
          "slot_index": 0
        },
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            893
          ],
          "shape": 3,
          "slot_index": 1
        }
      ],
      "properties": {
        "Node name for S&R": "ADE_AnimateDiffLoaderV1Advanced"
      },
      "widgets_values": [
        "release1008.ckpt",
        false,
        16,
        4,
        4,
        "uniform",
        true
      ],
      "color": "#323",
      "bgcolor": "#535"
    },
    {
      "id": 500,
      "type": "LoraLoader",
      "pos": [
        -903,
        1125
      ],
      "size": {
        "0": 315,
        "1": 126
      },
      "flags": {},
      "order": 4,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "MODEL",
          "link": 907
        },
        {
          "name": "clip",
          "type": "CLIP",
          "link": 910
        }
      ],
      "outputs": [
        {
          "name": "MODEL",
          "type": "MODEL",
          "links": [
            908
          ],
          "shape": 3,
          "slot_index": 0
        },
        {
          "name": "CLIP",
          "type": "CLIP",
          "links": [
            911
          ],
          "shape": 3,
          "slot_index": 1
        }
      ],
      "properties": {
        "Node name for S&R": "LoraLoader"
      },
      "widgets_values": [
        "Character_Kobeni.safetensors",
        1,
        1
      ]
    },
    {
      "id": 501,
      "type": "LoraLoader",
      "pos": [
        -918,
        1292
      ],
      "size": {
        "0": 315,
        "1": 126
      },
      "flags": {},
      "order": 5,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "MODEL",
          "link": 908
        },
        {
          "name": "clip",
          "type": "CLIP",
          "link": 911
        }
      ],
      "outputs": [
        {
          "name": "MODEL",
          "type": "MODEL",
          "links": [
            909
          ],
          "shape": 3,
          "slot_index": 0
        },
        {
          "name": "CLIP",
          "type": "CLIP",
          "links": [
            912
          ],
          "shape": 3,
          "slot_index": 1
        }
      ],
      "properties": {
        "Node name for S&R": "LoraLoader"
      },
      "widgets_values": [
        "ShinyOiledSkin_v20-LyCORIS.safetensors",
        0.39,
        1
      ]
    },
    {
      "id": 322,
      "type": "VAELoader",
      "pos": [
        -1171,
        580
      ],
      "size": {
        "0": 315,
        "1": 58
      },
      "flags": {},
      "order": 1,
      "mode": 0,
      "outputs": [
        {
          "name": "VAE",
          "type": "VAE",
          "links": [
            914
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "VAELoader"
      },
      "widgets_values": [
        "BerrysMix.vae.safetensors"
      ],
      "color": "#322",
      "bgcolor": "#533"
    },
    {
      "id": 398,
      "type": "PrimitiveNode",
      "pos": [
        -928,
        902
      ],
      "size": {
        "0": 210,
        "1": 82
      },
      "flags": {},
      "order": 2,
      "mode": 0,
      "outputs": [
        {
          "name": "INT",
          "type": "INT",
          "links": [
            895
          ],
          "widget": {
            "name": "seed",
            "config": [
              "INT",
              {
                "default": 0,
                "min": 0,
                "max": 18446744073709552000
              }
            ]
          },
          "slot_index": 0
        }
      ],
      "title": "Seed",
      "properties": {},
      "widgets_values": [
        438297115847873,
        "randomize"
      ],
      "color": "#233",
      "bgcolor": "#355"
    },
    {
      "id": 318,
      "type": "EmptyLatentImage",
      "pos": [
        -925,
        720
      ],
      "size": {
        "0": 315,
        "1": 106
      },
      "flags": {},
      "order": 3,
      "mode": 0,
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            905
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "EmptyLatentImage"
      },
      "widgets_values": [
        512,
        512,
        16
      ],
      "color": "#323",
      "bgcolor": "#535"
    },
    {
      "id": 496,
      "type": "KSampler (Efficient)",
      "pos": [
        667,
        646
      ],
      "size": {
        "0": 325,
        "1": 374
      },
      "flags": {},
      "order": 10,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "MODEL",
          "link": 894,
          "slot_index": 0
        },
        {
          "name": "positive",
          "type": "CONDITIONING",
          "link": 923,
          "slot_index": 1
        },
        {
          "name": "negative",
          "type": "CONDITIONING",
          "link": 892,
          "slot_index": 2
        },
        {
          "name": "latent_image",
          "type": "LATENT",
          "link": 893,
          "slot_index": 3
        },
        {
          "name": "optional_vae",
          "type": "VAE",
          "link": 914,
          "slot_index": 4
        },
        {
          "name": "script",
          "type": "SCRIPT",
          "link": null
        },
        {
          "name": "seed",
          "type": "INT",
          "link": 895,
          "widget": {
            "name": "seed",
            "config": [
              "INT",
              {
                "default": 0,
                "min": 0,
                "max": 18446744073709552000
              }
            ]
          },
          "slot_index": 6
        }
      ],
      "outputs": [
        {
          "name": "MODEL",
          "type": "MODEL",
          "links": [],
          "shape": 3,
          "slot_index": 0
        },
        {
          "name": "CONDITIONING+",
          "type": "CONDITIONING",
          "links": [],
          "shape": 3,
          "slot_index": 1
        },
        {
          "name": "CONDITIONING-",
          "type": "CONDITIONING",
          "links": [],
          "shape": 3,
          "slot_index": 2
        },
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            890
          ],
          "shape": 3,
          "slot_index": 3
        },
        {
          "name": "VAE",
          "type": "VAE",
          "links": [
            913
          ],
          "shape": 3,
          "slot_index": 4
        },
        {
          "name": "IMAGE",
          "type": "IMAGE",
          "links": null,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "KSampler (Efficient)"
      },
      "widgets_values": [
        "Sample",
        687836523153867,
        null,
        20,
        7.5,
        "dpmpp_2m",
        "karras",
        1,
        "none",
        "false"
      ],
      "color": "#332233",
      "bgcolor": "#553355",
      "shape": 1
    },
    {
      "id": 502,
      "type": "PreviewImage",
      "pos": [
        338,
        1082
      ],
      "size": {
        "0": 322.4598693847656,
        "1": 488.9253234863281
      },
      "flags": {},
      "order": 13,
      "mode": 0,
      "inputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "link": 916
        }
      ],
      "properties": {
        "Node name for S&R": "PreviewImage"
      }
    },
    {
      "id": 487,
      "type": "ADE_AnimateDiffCombine",
      "pos": [
        820,
        1070
      ],
      "size": {
        "0": 438.00616455078125,
        "1": 630.0061645507812
      },
      "flags": {},
      "order": 12,
      "mode": 0,
      "inputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "link": 850
        }
      ],
      "outputs": [
        {
          "name": "GIF",
          "type": "GIF",
          "links": null,
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "ADE_AnimateDiffCombine"
      },
      "widgets_values": [
        10,
        0,
        "final_outputGif/final_output",
        "video/h264-mp4",
        true,
        true
      ],
      "color": "#223",
      "bgcolor": "#335"
    },
    {
      "id": 319,
      "type": "CLIPSetLastLayer",
      "pos": [
        -542.3554374868759,
        1048.4256519698438
      ],
      "size": {
        "0": 210,
        "1": 58
      },
      "flags": {
        "collapsed": false
      },
      "order": 7,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 912
        }
      ],
      "outputs": [
        {
          "name": "CLIP",
          "type": "CLIP",
          "links": [
            527,
            879
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "title": "CLIP Skip",
      "properties": {
        "Node name for S&R": "CLIPSetLastLayer"
      },
      "widgets_values": [
        -2
      ],
      "color": "#432",
      "bgcolor": "#653"
    },
    {
      "id": 320,
      "type": "CLIPTextEncode",
      "pos": [
        -291,
        1127
      ],
      "size": {
        "0": 407.1927490234375,
        "1": 82.56219482421875
      },
      "flags": {},
      "order": 8,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 527
        }
      ],
      "outputs": [
        {
          "name": "CONDITIONING",
          "type": "CONDITIONING",
          "links": [
            892
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "title": "Negative Prompt",
      "properties": {
        "Node name for S&R": "CLIPTextEncode"
      },
      "widgets_values": [
        "(worst quality, low quality:1.4)"
      ],
      "color": "#322",
      "bgcolor": "#533"
    },
    {
      "id": 321,
      "type": "CLIPTextEncode",
      "pos": [
        -300,
        975
      ],
      "size": {
        "0": 407.1927490234375,
        "1": 87.56219482421875
      },
      "flags": {},
      "order": 9,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 879,
          "slot_index": 0
        }
      ],
      "outputs": [
        {
          "name": "CONDITIONING",
          "type": "CONDITIONING",
          "links": [
            923
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "title": "Prompt",
      "properties": {
        "Node name for S&R": "CLIPTextEncode"
      },
      "widgets_values": [
        "LOL"
      ],
      "color": "#232",
      "bgcolor": "#353"
    },
    {
      "id": 317,
      "type": "CheckpointLoaderSimpleWithNoiseSelect",
      "pos": [
        -1342,
        1026
      ],
      "size": {
        "0": 403.0302734375,
        "1": 126.1493148803711
      },
      "flags": {},
      "order": 0,
      "mode": 0,
      "outputs": [
        {
          "name": "MODEL",
          "type": "MODEL",
          "links": [
            907
          ],
          "shape": 3,
          "slot_index": 0
        },
        {
          "name": "CLIP",
          "type": "CLIP",
          "links": [
            910
          ],
          "shape": 3,
          "slot_index": 1
        },
        {
          "name": "VAE",
          "type": "VAE",
          "links": null,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "CheckpointLoaderSimpleWithNoiseSelect"
      },
      "widgets_values": [
        "yoinkoor.fp16.safetensors",
        "sqrt_linear (AnimateDiff)"
      ],
      "color": "#432",
      "bgcolor": "#653"
    }
  ],
  "links": [
    [
      527,
      319,
      0,
      320,
      0,
      "CLIP"
    ],
    [
      850,
      334,
      0,
      487,
      0,
      "IMAGE"
    ],
    [
      879,
      319,
      0,
      321,
      0,
      "CLIP"
    ],
    [
      890,
      496,
      3,
      334,
      0,
      "LATENT"
    ],
    [
      892,
      320,
      0,
      496,
      2,
      "CONDITIONING"
    ],
    [
      893,
      486,
      1,
      496,
      3,
      "LATENT"
    ],
    [
      894,
      486,
      0,
      496,
      0,
      "MODEL"
    ],
    [
      895,
      398,
      0,
      496,
      6,
      "INT"
    ],
    [
      905,
      318,
      0,
      486,
      1,
      "LATENT"
    ],
    [
      907,
      317,
      0,
      500,
      0,
      "MODEL"
    ],
    [
      908,
      500,
      0,
      501,
      0,
      "MODEL"
    ],
    [
      909,
      501,
      0,
      486,
      0,
      "MODEL"
    ],
    [
      910,
      317,
      1,
      500,
      1,
      "CLIP"
    ],
    [
      911,
      500,
      1,
      501,
      1,
      "CLIP"
    ],
    [
      912,
      501,
      1,
      319,
      0,
      "CLIP"
    ],
    [
      913,
      496,
      4,
      334,
      1,
      "VAE"
    ],
    [
      914,
      322,
      0,
      496,
      4,
      "VAE"
    ],
    [
      916,
      334,
      0,
      502,
      0,
      "IMAGE"
    ],
    [
      923,
      321,
      0,
      496,
      1,
      "CONDITIONING"
    ]
  ],
  "groups": [
    {
      "title": "Txt2Gif / Img2Gif",
      "bounding": [
        -1435,
        369,
        2721,
        1405
      ],
      "color": "#3f789e",
      "font_size": 24
    }
  ],
  "config": {},
  "extra": {},
  "version": 0.4
}

**Comment by ezra-ch** [comment]
ok nvm i am stupid, you have to enable dev mode in the settings then save in api format
